import "server-only";

import { DrizzleAdapter } from "@auth/drizzle-adapter";
import NextAuth from "next-auth";
import type { Adapter, AdapterUser } from "next-auth/adapters";
import type { NextAuthConfig } from "next-auth";
import GitHub from "next-auth/providers/github";
import Google from "next-auth/providers/google";
import { STARTING_CREDITS } from "@/data/credits";
import { getDatabase, withDatabaseTransaction } from "@/db/client";
import {
  accounts,
  creditEntries,
  sessions,
  users,
  verificationTokens,
} from "@/db/schema";
import {
  configuredProviderNames,
  isAuthConfigured,
  isTrustedProviderEmail,
} from "@/lib/auth-config";

export { isAuthConfigured, configuredProviderNames };

/**
 * `allowDangerousEmailAccountLinking` lets one person use either button on one
 * email: the second provider joins the existing user rather than being
 * refused, so there is one account and one ledger. Linking sets
 * `isNewUser = false`, so the adapter's `createUser` never runs and no second
 * starting grant is written. The `signIn` callback below is what makes the
 * flag safe — without it this would trust an unverified address.
 */
function configuredProviders() {
  const providers = [];
  const names = configuredProviderNames();
  if (names.includes("github")) {
    providers.push(GitHub({ allowDangerousEmailAccountLinking: true }));
  }
  if (names.includes("google")) {
    providers.push(Google({ allowDangerousEmailAccountLinking: true }));
  }
  return providers;
}

/**
 * Wraps the adapter's `createUser` so account creation and the starting credit
 * grant happen inside one transaction: a user row can never exist without a
 * grant row. The partial unique index on `credit_entries` (kind = 'grant') is
 * what actually stops a double grant under concurrency; this transaction is
 * what stops a user existing with no grant at all.
 */
function withStartingGrant(adapter: Adapter): Adapter {
  return {
    ...adapter,
    async createUser(data) {
      // `id` is generated by the DB default (uuid().defaultRandom()); drop the
      // adapter's placeholder rather than insert it.
      const insert = { ...data };
      delete (insert as Partial<typeof data>).id;
      return withDatabaseTransaction(async (transaction) => {
        const [user] = await transaction
          .insert(users)
          .values(insert)
          .returning();
        await transaction.insert(creditEntries).values({
          userId: user!.id,
          kind: "grant",
          amount: STARTING_CREDITS,
          reason: "signup",
        });
        // Auth.js's AdapterUser types email as non-nullable; our column allows
        // null so anonymous/no-email providers never break the insert. Cast
        // rather than widen the column for this one caller.
        return user as unknown as AdapterUser;
      });
    },
  };
}

function buildConfig(): NextAuthConfig {
  if (!isAuthConfigured()) {
    return { providers: [], pages: { signIn: "/sign-in" }, trustHost: true };
  }
  return {
    adapter: withStartingGrant(
      DrizzleAdapter(getDatabase(), {
        usersTable: users,
        accountsTable: accounts,
        sessionsTable: sessions,
        verificationTokensTable: verificationTokens,
      }),
    ),
    session: { strategy: "database" },
    providers: configuredProviders(),
    pages: { signIn: "/sign-in" },
    trustHost: true,
    callbacks: {
      signIn({ account, profile }) {
        if (!account) return true;
        return isTrustedProviderEmail(account.provider, profile);
      },
      session({ session, user }) {
        session.user.id = user.id;
        return session;
      },
    },
  };
}

export const { handlers, signIn, signOut, auth } = NextAuth(buildConfig());

export type AccountResult =
  | {
      ok: true;
      userId: string;
      email: string | null;
      name: string | null;
      image: string | null;
    }
  | { ok: false; reason: "unconfigured" | "unauthenticated" };

/**
 * The auth boundary every gated route/page goes through. Returns
 * `unconfigured` without calling `auth()` when Auth.js isn't configured, which
 * is what keeps unconfigured builds, CI, and Playwright's keyless production
 * server from ever exercising a session lookup — and what keeps statically
 * rendered routes static.
 */
export async function requireAccount(): Promise<AccountResult> {
  if (!isAuthConfigured()) return { ok: false, reason: "unconfigured" };
  const session = await auth();
  if (!session?.user?.id) return { ok: false, reason: "unauthenticated" };
  return {
    ok: true,
    userId: session.user.id,
    email: session.user.email ?? null,
    name: session.user.name ?? null,
    image: session.user.image ?? null,
  };
}
